title: Blackbox Records
description: Experimental record label with a focus on boundary-pushing music.
social_image: /assets/images/brand/logo.png
social_image_alt: "Blackbox Records logo"
url: "https://zantoichi.github.io"
baseurl: "/blackbox-records"
permalink: pretty
exclude:
  - compressed-repo.md
  - vendor
  - vendor/bundle
  - .bundle
  - node_modules
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-sitemap
collections:
  artists:
    output: true
    permalink: /artists/:slug/
  releases:
    output: true
    permalink: /releases/:name/
  news:
    output: true
    permalink: /news/:name/
