title: Blackbox Records
description: Experimental record label with a focus on boundary-pushing music.
url: ""
baseurl: ""
permalink: pretty
exclude:
  - compressed-repo.md
collections:
  releases:
    output: true
    permalink: /releases/:name/
  news:
    output: true
    permalink: /news/:name/
